// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhhOtsBmRoL9U_g9EYo--vs5RYWxiJ3AM',
    appId: '1:720181125850:web:b00e466e96988a73c07be3',
    messagingSenderId: '720181125850',
    projectId: 'chatapp-1a250',
    authDomain: 'chatapp-1a250.firebaseapp.com',
    storageBucket: 'chatapp-1a250.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0vCn_s563KuAMzM9mrb3EBRniZG3bvrA',
    appId: '1:720181125850:android:abc317e8f23a8ba9c07be3',
    messagingSenderId: '720181125850',
    projectId: 'chatapp-1a250',
    storageBucket: 'chatapp-1a250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVapRpRkPb4HnMKMQYFvITRjseLa8bIdE',
    appId: '1:720181125850:ios:9190c4cecaefa8dfc07be3',
    messagingSenderId: '720181125850',
    projectId: 'chatapp-1a250',
    storageBucket: 'chatapp-1a250.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVapRpRkPb4HnMKMQYFvITRjseLa8bIdE',
    appId: '1:720181125850:ios:9190c4cecaefa8dfc07be3',
    messagingSenderId: '720181125850',
    projectId: 'chatapp-1a250',
    storageBucket: 'chatapp-1a250.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhhOtsBmRoL9U_g9EYo--vs5RYWxiJ3AM',
    appId: '1:720181125850:web:83758287ffa3905bc07be3',
    messagingSenderId: '720181125850',
    projectId: 'chatapp-1a250',
    authDomain: 'chatapp-1a250.firebaseapp.com',
    storageBucket: 'chatapp-1a250.appspot.com',
  );
}
